using System.Threading.Tasks;
using Hast.Layer;

namespace Hast.Samples.Consumer.SampleRunners
{
    /// <summary>
    /// Configures and runs a sample.
    /// </summary>
    public interface ISampleRunner
    {
        /// <summary>
        /// Uses <paramref name="configuration"/> to initialize the sample.
        /// </summary>
        void Configure(HardwareGenerationConfiguration configuration);

        /// <summary>
        /// Executes the sample.
        /// </summary>
        /// <param name="hastlayer">The <see cref="Hastlayer"/> instance.</param>
        /// <param name="hardwareRepresentation">The hardware generated by <paramref name="hastlayer"/>.</param>
        /// <param name="configuration">The configuration used to proxy the .Net code.</param>
        Task RunAsync(IHastlayer hastlayer, IHardwareRepresentation hardwareRepresentation, IProxyGenerationConfiguration configuration);
    }
}
