<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Title>Hastlayer - Common</Title>
    <Description>Some types and services common for all Hastlayer components. See the project website for detailed documentation.</Description>
    <PackageTags>Lombiq;Hastlayer;FPGA;HardwareAcceleration;Performance</PackageTags>
    <PackageProjectUrl>https://github.com/Lombiq/Hastlayer-SDK/tree/dev/src/Hastlayer/Hast.Common</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.HelpfulLibraries.Common" Version="13.0.0" />
  </ItemGroup>
</Project>
